window.CHARACTER_LAYOUT_CONFIG = {
  global: {
    stageScaleMultiplier: 0.80,
    summaryScaleMultiplier: 0.90,
  },
  characters: {
    "Audrey":    { stageSingle: 1.02, stageDouble: 0.98, summary: 1.05, stageOffset: { x: 0, y: -60 }, summaryOffset: { x: -4, y: -6 } },
    "Bai Mo":    { stageSingle: 1.02, stageDouble: 0.98, summary: 1.05, stageOffset: { x: 0, y: -60 }, summaryOffset: { x: -4, y: -6 } },
    "Celestia":  { stageSingle: 1.02, stageDouble: 0.98, summary: 1.05, stageOffset: { x: 0, y: -60 }, summaryOffset: { x: -4, y: -6 } },
    "Chiyo":     { stageSingle: 1.02, stageDouble: 0.98, summary: 1.05, stageOffset: { x: 0, y: -60 }, summaryOffset: { x: -4, y: -6 } },
    "Cielle":    { stageSingle: 1.02, stageDouble: 0.98, summary: 1.05, stageOffset: { x: 0, y: -60 }, summaryOffset: { x: -4, y: -6 } },
    "Eika":      { stageSingle: 1.02, stageDouble: 0.98, summary: 1.05, stageOffset: { x: 0, y: -60 }, summaryOffset: { x: -4, y: -6 } },
    "Flavia":    { stageSingle: 1.02, stageDouble: 0.98, summary: 1.05, stageOffset: { x: 0, y: -60 }, summaryOffset: { x: -4, y: -6 } },
    "Fragrans":  { stageSingle: 1.02, stageDouble: 0.98, summary: 1.05, stageOffset: { x: 0, y: -60 }, summaryOffset: { x: -4, y: -6 } },
    "Fuchsia":   { stageSingle: 1.02, stageDouble: 0.98, summary: 1.05, stageOffset: { x: 0, y: -60 }, summaryOffset: { x: -4, y: -6 } },
    "Galatea":   { stageSingle: 1.02, stageDouble: 0.98, summary: 1.05, stageOffset: { x: 0, y: -60 }, summaryOffset: { x: -4, y: -6 } },
    "Kanami":    { stageSingle: 1.02, stageDouble: 0.98, summary: 1.05, stageOffset: { x: 0, y: -60 }, summaryOffset: { x: -4, y: -6 } },
    "Kokona":    { stageSingle: 1.02, stageDouble: 0.98, summary: 1.05, stageOffset: { x: 0, y: -60 }, summaryOffset: { x: -4, y: -6 } },
    "Lawine":    { stageSingle: 1.02, stageDouble: 0.98, summary: 1.05, stageOffset: { x: 0, y: -60 }, summaryOffset: { x: -4, y: -6 } },
    "Leona":     { stageSingle: 1.02, stageDouble: 0.98, summary: 1.05, stageOffset: { x: 0, y: -60 }, summaryOffset: { x: -4, y: -6 } },
    "Maddelena": { stageSingle: 1.02, stageDouble: 0.98, summary: 1.05, stageOffset: { x: 0, y: -60 }, summaryOffset: { x: -4, y: -6 } },
    "Mara":      { stageSingle: 1.02, stageDouble: 0.98, summary: 1.05, stageOffset: { x: 0, y: -60 }, summaryOffset: { x: -4, y: -6 } },
    "Meredith":  { stageSingle: 1.02, stageDouble: 0.98, summary: 1.05, stageOffset: { x: 0, y: -60 }, summaryOffset: { x: -4, y: -6 } },
    "Michele":   { stageSingle: 1.02, stageDouble: 0.98, summary: 1.05, stageOffset: { x: 0, y: -60 }, summaryOffset: { x: -4, y: -6 } },
    "Ming":      { stageSingle: 1.02, stageDouble: 0.98, summary: 1.05, stageOffset: { x: 0, y: -60 }, summaryOffset: { x: -4, y: -6 } },
    "Nobunaga":  { stageSingle: 1.02, stageDouble: 0.98, summary: 1.05, stageOffset: { x: 0, y: -60 }, summaryOffset: { x: -4, y: -6 } },
    "Reiichi":   { stageSingle: 1.02, stageDouble: 0.98, summary: 1.05, stageOffset: { x: 0, y: -60 }, summaryOffset: { x: -4, y: -6 } },
    "Yugiri":    { stageSingle: 1.02, stageDouble: 0.98, summary: 1.05, stageOffset: { x: 0, y: -60 }, summaryOffset: { x: -4, y: -6 } },
    "Yvette":    { stageSingle: 1.02, stageDouble: 0.98, summary: 1.05, stageOffset: { x: 0, y: -60 }, summaryOffset: { x: -4, y: -6 } },
  }
};
